[project]
name = "roboto-s3-integration-lambda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-lambda-powertools>=3.20.0",
    "roboto>=0.27.0",
]
